In [1]:
import numpy as np

In [17]:
ar = np.array([[1,2,3]])
ar2 = np.array([[2,3,4]])
print(ar*ar2)
#print(ar.T)

[[ 2  6 12]]


In [39]:
strng = np.array(["hello", "whatever"])
print(strng)
strng = np.append(strng, "lll" )
print(strng)

['hello' 'whatever']
['hello' 'whatever' 'lll']


In [46]:
arrr = np.array([[1,2,3],[4,5,6]])
print(arrr)

[[1 2 3]
 [4 5 6]]


In [53]:
np.random.seed(0)
rnd = np.random.normal(10, 2, 10)

In [54]:
print(rnd)

[13.52810469 10.80031442 11.95747597 14.4817864  13.73511598  8.04544424
 11.90017684  9.69728558  9.7935623  10.821197  ]


In [68]:
arr = np.array([rnd]).transpose()

In [69]:
print(arr)

[[13.52810469]
 [10.80031442]
 [11.95747597]
 [14.4817864 ]
 [13.73511598]
 [ 8.04544424]
 [11.90017684]
 [ 9.69728558]
 [ 9.7935623 ]
 [10.821197  ]]
